language: python
python:
    - '3.6'
sudo: required
before_install:
    - sudo apt-get update
    - sudo apt-get install -y --no-install-recommends texlive-base
    - sudo apt-get install -y --no-install-recommends texlive-latex-base
    - sudo apt-get install -y texlive-latex-recommended 
    - sudo apt-get install -y texlive-latex-extra
    - sudo apt-get install -y texlive-fonts-recommended
    - sudo apt-get install -y --no-install-recommends latexmk
    - sudo apt-get install -y --no-install-recommends graphviz
script:
    - export CORRECT_TRAVIS_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - . ./travis-setup.sh
    - paver build_all
    - touch _build/html/.nojekyll
    - ./travis-move.sh
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: _build/html
    on:
        condition: $IS_DEPLOYABLE = Y
        all_branches: true
